name: pr-echo
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo-title
        run: echo "Reviewing PR: ${{ github.event.pull_request.title }}"
      - name: checkout-head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: run-pr-script
        run: |
          echo "running PR contributed code in base context"
          ls -la
